### PR TITLE
Made Enhancements Added New Features

### PR DESCRIPTION
**Pull request by aahnik**
# here is a list of changes
[read new readme](https://github.com/aahnik/Simple-Yet-Hackable-WhatsApp-api#simple-yet-hackable-whatsapp-api)
1. **Removed emojify and related mechanism**
2. **Updated Readme showing how to use Formatting and Emojis**
3. Added **new feature**
> # send dynamic bulk messages using just a csv file and template string
The csv must have headers and NAME colomn is must
Variables inside template string must be prefixed with dollar sign
4. **Updated Readme explaining new feature** new screen shots added
5. removed __pycache__
6. **Removed unused variables like `person`**
### the info is clearly mentioned in readme Please read the new Readme for details
# [read new readme](https://github.com/aahnik/Simple-Yet-Hackable-WhatsApp-api#simple-yet-hackable-whatsapp-api)

### CODE REVIEW

**Comment by VISWESWARAN1998** [comment]
Once again thank you for your contribution.

But the new pull request is reducing the quality of Readme file. The main aim of the application to is to automate the WhatsApp web. Adding CSV will add more complications like every users might have their own file format like excel, even database technologies. 

I do have an example demo software which uses this API and performs all the necessary functions which you have specified. 

Have a look at this demo application which is made using Python:
https://www.youtube.com/watch?v=kQgwyyOgp98

If you are interested I will make this example application as opensource.


I have also planned a few more features which I have to implement. Like I am planning to separate code from data e.g whatsapp generally updates its UI more frequently which results in changed XPATH and CSS Selectors thereby breaking the API. 

Since this API has code and data together in a single class, the deployed application which uses this API is needed to be rebuilt.  So I am planning to add XPATHS in seperate JSON file and import it via code. 

Thank you and Regards,
Visweswaran N

**Comment by aahnik** [comment]
**Thanks a lot for your review.**
I also thought of seperating all css/xpath selection outside the whatsapp.py file.

Yes, api breaks often as whatsapp changes its website structure.

**I understand that many people may use database or excel**

Google sheets, MS Excel, Libre Office, all have options to generate CSV .
CSV can also be generated from database using few lines of code.

I thought making a inbuilt function would benefit many people.

## Can I  rather tweak the method and use a list of dictionary instead of CSV?

I think having an inbuilt batch sender can be beneficial.

**Comment by aahnik** [comment]
Please consider the readme once again.

I think the conventions of codacy automatic code review  is not apt always.

**I am new to GitHub, I may not be aware of all best practises.**

# Please suggest what can I improve in Readme .
## I have kept everything intact other than adding few stuff in the front.

The codacy code review is unsatisfied with the hierarchy of headings and usage of bold inside headings.

But in my opinion, the readme file visually looks good

# [See the new readme]( )

**Comment by aahnik** [comment]
@VISWESWARAN1998 

> Have a look at this demo application which is made using Python:
> https://www.youtube.com/watch?v=kQgwyyOgp98

# that's great.

## I went to your YouTube channel.
You had a public playlist called "LIFE"  . The songs are great .

Many of the songs were already my favourites and in my playlist.

 I believe We( @aahnik  and @VISWESWARAN1998 ) share **common spiritual philosophy in life.**

I would like to contact you personally @VISWESWARAN1998 .
🙂
# I would be extremely grateful if you [chat with me](https://t.me/AahniKDaw)
Or please reply to my email .

**Comment by aahnik** [comment]
# i have improved the Readme to satisfy the criterion of Codacy/PR Quality Review
Screenshot from 2020-07-07 01-08-46

**Comment by aahnik** [comment]
I have made changes solving #56 and #54 part 7 solved #48 in a modular approach for send_message, send_document,send_picture

**Comment by aahnik** [comment]
I have made changes solving #56 and #54 part 7 solved #48 in a modular approach for send_message, send_document,send_picture
##  @bhavya32  i tried to solve your problem see my pull request #53 added new commits recently 
### do a test run 
# you can see my version of whatsapp api which i forked from @VISWESWARAN1998 [here](https://github.com/aahnik/Simple-Yet-Hackable-WhatsApp-api)

**Pull request closed without merging**
